// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/convert": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "SVG2PNG"
                ],
                "summary": "Convert an SVG image to a PNG image with the specified dimensions.",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 512,
                        "description": "Width of the resulting PNG image",
                        "name": "width",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 512,
                        "description": "Height of the resulting PNG image",
                        "name": "height",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "svg url to convert",
                        "name": "svg_url",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Binary PNG data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "svg2png.kmoz.dev",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Swagger SVG to PNG API",
	Description:      "Convert an SVG image to a PNG image with the specified dimensions.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
